apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: bootc-image-builder
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: bootc-image-builder
    app.kubernetes.io/part-of: bootc-image-builder
  name: bootc-image-builderqpe1
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: bootc-image-builder
    weight: 100
status: {}
